default:
  golem_name: bgScorer
  golem_version: 0.0.0.9000
  app_prod: no
  bg_games_dir: interactive_saved_games
  results_sheet: Completed
  use_gcs: !expr getOption("bgScorer.use_gcs", FALSE)
test:
  bg_games_dir: test_saved_games
production:
  app_prod: yes
  bg_games_dir: saved_games
  use_gcs: TRUE
dev:
  golem_wd: !expr pkgload::pkg_path()
