# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: shiny-deploy

env: 
  GOOGLE_CREDS_BASE: ${{ secrets.GOOGLE_CREDS_BASE }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GAC }}
  SS_ID: ${{ secrets.SS_ID }}

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.
          needs: deploy, check
          
      - name: Configure gs4_auth
        run: |
          renviron <- Sys.getenv(
            GOOGLE_APPLICATION_CREDENTIALS,
            SS_ID
          )
          writeLines(paste0(names(renviron), "=", renviron), ".Renviron")
          bgScorer::google_auth_config(pk = "${{ secrets.GOOGLE_PK }}")
          
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          check-dir: '"check"'

      - name: Authorize and deploy app
        run: |
          rsconnect::setAccountInfo("${{ secrets.RSCONNECT_USER }}",
                                    "${{ secrets.RSCONNECT_TOKEN }}",
                                    "${{ secrets.RSCONNECT_SECRET }}")
          rsconnect::deployApp(appFiles = c("app.R",
                                            "table.csv",
                                            "round.csv",
                                            "DESCRIPTION",
                                            "NAMESPACE",
                                            "R",
                                            "inst",
                                            ".Renviron",
                                            "${{ secrets.GAC }}"))
        shell: Rscript {0}
        
