# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: shiny-deploy

jobs:
  shiny-deploy:
    env:
      GCS_DEFAULT_BUCKET: ${{ secrets.GCS_DEFAULT_BUCKET }}
      BGSCORER_PASSWORD: ${{ secrets.BGSCORER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 'release'
          
      - name: Add some R options for later steps
        run: |
          cat("\noptions(pkg.include_linkingto = TRUE)\n", file = "~/.Rprofile", append = TRUE)
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.
          needs: deploy
          
      - name: Configure gs4_auth
        run: |
          env_vars <- c(
            "BGSCORER_PASSWORD",
            "GCS_DEFAULT_BUCKET"
          )
          renviron <- Sys.getenv(env_vars, names = TRUE)
          writeLines(paste0(names(renviron), "=", renviron), ".Renviron")
        shell: Rscript {0}

      - name: Authorize and deploy app
        run: |
          rsconnect::setAccountInfo("${{ secrets.RSCONNECT_USER }}",
                                    "${{ secrets.RSCONNECT_TOKEN }}",
                                    "${{ secrets.RSCONNECT_SECRET }}")
                                    
          rsconnect::deployApp(
            appName = "Betting-Game-Scorer",
            appDir = "inst/app",
            appFiles = c("app.R", "www", ".Renviron"),
            forceUpdate = TRUE
          )
          
        shell: Rscript {0}
        
